import Ginzburg333

/- Run after the library successfully builds. Selected important declarations. -/
#print axioms Ginzburg333.CyclicData.productSpan_eq_top
#print axioms Ginzburg333.CyclicData.plane_contains_rank_two
#print axioms Ginzburg333.CyclicData.adjacent_range_eq_dot_ker
#print axioms Ginzburg333.CyclicData.annihilator_eq_adjacent_image
#print axioms Ginzburg333.CyclicData.plane_colon_closed
#print axioms Ginzburg333.CyclicData.full_colon_closed
#print axioms Ginzburg333.CyclicData.multiply_assoc
#print axioms Ginzburg333.Homology.quotient_exact_of_exact
#print axioms Ginzburg333.Homology.filtration_induction
#print axioms Ginzburg333.Signs.comparison_parity
#print axioms Ginzburg333.Ginzburg.cohomologicalDegree_eq_length_sub_weight
#print axioms Ginzburg333.CyclicData.rowGenerated_right_stable
#print axioms Ginzburg333.CyclicData.exists_filtrationStep
#print axioms Ginzburg333.CyclicData.FiltrationStep.short_exact
#print axioms Ginzburg333.CyclicData.FiltrationStep.inclusion_degree
#print axioms Ginzburg333.CyclicData.FiltrationStep.inclusion_action
#print axioms Ginzburg333.Ginzburg.differential_term_valid
#print axioms Ginzburg333.Ginzburg.differential_cohomological
#print axioms Ginzburg333.Ginzburg.finite_internal_basis
#print axioms Ginzburg333.Homology.exactAt_dual
#print axioms Ginzburg333.Ginzburg.freeDifferential_leibniz
#print axioms Ginzburg333.Ginzburg.differential_square
#print axioms Ginzburg333.Ginzburg.componentDifferential_square
#print axioms Ginzburg333.Ginzburg.ginzburgRegular_of_internal_primitives
#print axioms Ginzburg333.Bar.positiveMultiplication_assoc
#print axioms Ginzburg333.Bar.ambientDifferential_square
#print axioms Ginzburg333.Bar.normalizedDifferential_square
#print axioms Ginzburg333.Bar.filtration_normalized_short_exact
#print axioms Ginzburg333.Bar.filtration_internal_short_exact
#print axioms Ginzburg333.Bar.internalProjection_differential
#print axioms Ginzburg333.Bar.rowContraction_homotopy_normalized
#print axioms Ginzburg333.Bar.internallyNormalized_zero_surjective
#print axioms Ginzburg333.Bar.normalized_bar_off_diagonal
#print axioms Ginzburg333.Bar.simple_normalized_bar_off_diagonal
#print axioms Ginzburg333.Bar.simpleScalarMap_differential
#print axioms Ginzburg333.Comparison.simpleBarDualCoordinates_apply
#print axioms Ginzburg333.Comparison.signCoordinates_square
#print axioms Ginzburg333.Comparison.rowPathComponent_bigraded
#print axioms Ginzburg333.Comparison.generator_structure_coefficient
#print axioms Ginzburg333.Comparison.simple_dual_bar_off_diagonal
#print axioms Ginzburg333.Comparison.cobarBasis_internal
#print axioms Ginzburg333.Comparison.cobarBasis_length
#print axioms Ginzburg333.Comparison.signedWordReversal_differential
#print axioms Ginzburg333.Comparison.cobarBasis_transpose
#print axioms Ginzburg333.Comparison.finiteDualReversal_differential
#print axioms Ginzburg333.Comparison.totalDualReversal_differential
#print axioms Ginzburg333.Comparison.ginzburg_internal_primitives
#print axioms Ginzburg333.tensorRegular_ginzburgRegular
#print axioms Ginzburg333.Comparison.tensorRegular_ginzburgRegular_chosen_bases
#check Ginzburg333.tensorRegular_ginzburgRegular
#print axioms Ginzburg333.Ginzburg.ginzburgRegular_contraction_ne_zero
#print axioms Ginzburg333.Ginzburg.negativeDifferential_exact
#print axioms Ginzburg333.Ginzburg.internalJacobi_finrank_euler
#print axioms Ginzburg333.Ginzburg.internalJacobi_quadratic_growth
#print axioms Ginzburg333.Ginzburg.internalJacobi_finrank_36
#print axioms Ginzburg333.Converse.rankOneSlice_exists
#print axioms Ginzburg333.Converse.freeCornerData_exists
#print axioms Ginzburg333.Converse.pathMatrixEvaluation_differential
#print axioms Ginzburg333.Converse.liftFreeWord_entry00
#print axioms Ginzburg333.Converse.freeCorner_exponential_lower_bound
#print axioms Ginzburg333.ginzburgRegular_tensorRegular
#print axioms Ginzburg333.ginzburgRegular_iff_tensorRegular
#print axioms Ginzburg333.Comparison.ginzburgRegular_iff_tensorRegular_chosen_bases
#check Ginzburg333.ginzburgRegular_tensorRegular
#check Ginzburg333.ginzburgRegular_iff_tensorRegular
