import Ginzburg333.Finite.Corner

/-!
# Two-generator colon calculations

All submodules are submodules of the actual eight-dimensional row space.
`rowGenerated U` is the sum of the images of multiplication by elements of U,
not a dimension-only proxy for the generated ideal.

Status: compiled and kernel-checked with Lean 4.19.0.
-/

namespace Ginzburg333
open Module
variable {k : Type*} [Field k]

/-- Rows whose degree-zero part is zero and degree-one part lies in U. -/
def planeRows (U : Submodule k (Vec k)) : Submodule k (Row k) :=
  (⊥ : Submodule k k).prod (U.prod (⊤ : Submodule k (Vec k × k)))

@[simp] theorem mem_planeRows (U : Submodule k (Vec k))
    (s : k) (a b : Vec k) (t : k) :
    (s, a, b, t) ∈ planeRows U ↔ s = 0 ∧ a ∈ U := by
  simp [planeRows, Submodule.mem_prod]

/-- Injection of the degree-two piece into a row. -/
def rowDegreeTwo : Vec k →ₗ[k] Row k where
  toFun z := (0, 0, z, 0)
  map_add' := by intros; simp
  map_smul' := by intros; simp

namespace CyclicData

def rowGenerated (D : CyclicData k) (i : Vertex) (U : Submodule k (Vec k)) :
    Submodule k (Row k) :=
  ⨆ a : U, LinearMap.range (D.leftOne i (a : Vec k))

theorem leftOne_mem_rowGenerated (D : CyclicData k) (i : Vertex)
    (U : Submodule k (Vec k)) {a : Vec k} (ha : a ∈ U) (r : Row k) :
    D.leftOne i a r ∈ D.rowGenerated i U :=
  (le_iSup (fun x : U => LinearMap.range (D.leftOne i (x : Vec k)))
    ⟨a, ha⟩) ⟨r, rfl⟩

/-- The generated ideal for every parameter subspace of dimension at least two. -/
theorem rowGenerated_eq_planeRows (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) (U : Submodule k (Vec k)) (hU : 2 ≤ finrank k U) :
    D.rowGenerated i U = planeRows U := by
  classical
  apply le_antisymm
  · apply iSup_le
    intro a
    rintro r ⟨s, rfl⟩
    apply (mem_planeRows U _ _ _ _).mpr
    exact ⟨rfl, U.smul_mem s.1 a.property⟩
  · rintro ⟨s, y, z, t⟩ hmem
    obtain ⟨hs, hy⟩ := (mem_planeRows U s y z t).mp hmem
    subst s
    have h1 : (0, y, 0, 0) ∈ D.rowGenerated i U := by
      simpa [leftOne] using D.leftOne_mem_rowGenerated i U hy (1, 0, 0, 0)
    have hprod : D.productSpan i U ≤
        (D.rowGenerated i U).comap rowDegreeTwo := by
      apply iSup_le
      intro a
      rintro v ⟨b, rfl⟩
      change (0, 0, D.mul i (a : Vec k) b, 0) ∈ D.rowGenerated i U
      simpa [leftOne] using D.leftOne_mem_rowGenerated i U a.property (0, b, 0, 0)
    have h2 : (0, 0, z, 0) ∈ D.rowGenerated i U := by
      apply hprod
      rw [D.productSpan_eq_top_of_two_le hD i U hU]
      trivial
    have hUne : U ≠ ⊥ := by
      intro h
      rw [h, finrank_bot] at hU
      omega
    obtain ⟨a, ha, ha0⟩ := (Submodule.ne_bot_iff U).mp hUne
    obtain ⟨v, hv⟩ := dotMap_surjective ha0 t
    have h3 : (0, 0, 0, t) ∈ D.rowGenerated i U := by
      have hh := D.leftOne_mem_rowGenerated i U ha (0, 0, v, 0)
      change dot a v = t at hv
      simpa [leftOne, hv] using hh
    have hh := (D.rowGenerated i U).add_mem
      ((D.rowGenerated i U).add_mem h1 h2) h3
    simpa using hh

/-- Product span of a plane generated by a and g is the sum of two images. -/
theorem ranges_sup_eq_top (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) (a g : Vec k)
    (hplane : finrank k (Submodule.span k ({a, g} : Set (Vec k))) = 2) :
    LinearMap.range (D.mul i a) ⊔ LinearMap.range (D.mul i g) = ⊤ := by
  let U := Submodule.span k ({a, g} : Set (Vec k))
  let P := LinearMap.range (D.mul i a) ⊔ LinearMap.range (D.mul i g)
  have hle : D.productSpan i U ≤ P := by
    apply iSup_le
    intro x
    rintro v ⟨b, rfl⟩
    have hU : U ≤ P.comap ((D.mul i).flip b) := by
      apply Submodule.span_le.mpr
      intro z hz
      rcases Set.mem_insert_iff.mp hz with hz | hz
      · subst z
        exact (show LinearMap.range (D.mul i a) ≤ P from le_sup_left) ⟨b, rfl⟩
      · have hz' := Set.mem_singleton_iff.mp hz
        subst z
        exact (show LinearMap.range (D.mul i g) ≤ P from le_sup_right) ⟨b, rfl⟩
    exact hU x.property
  have htop : D.productSpan i U = ⊤ := D.productSpan_eq_top hD i U hplane
  exact top_le_iff.mp (htop ▸ hle)

/-- The degree-one subspace of the two-generator colon. -/
def colonPlane (D : CyclicData k) (i : Vertex) (a g : Vec k) :
    Submodule k (Vec k) :=
  (LinearMap.range (D.mul i a)).comap (D.mul i g)

/-- The full, all-degree colon formula before using its dimension. -/
theorem colon_eq_planeRows (D : CyclicData k) (i : Vertex) {a g : Vec k}
    (ha : a ≠ 0) (hg : g ∉ Submodule.span k {a}) :
    (LinearMap.range (D.leftOne i a)).comap (D.leftOne i g) =
      planeRows (D.colonPlane i a g) := by
  classical
  ext r
  rcases r with ⟨s, y, z, t⟩
  constructor
  · rintro ⟨q, hq⟩
    have h1 : q.1 • a = s • g :=
      congrArg (fun r : Row k => r.2.1) hq
    have h2 : D.mul i a q.2.1 = D.mul i g y :=
      congrArg (fun r : Row k => r.2.2.1) hq
    have hs : s = 0 := by
      by_contra hs
      apply hg
      have hsg : s • g ∈ Submodule.span k {a} := by
        rw [← h1]
        exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))
      have hh := (Submodule.span k {a}).smul_mem s⁻¹ hsg
      simpa [smul_smul, hs] using hh
    apply (mem_planeRows _ _ _ _ _).mpr
    exact ⟨hs, ⟨q.2.1, h2⟩⟩
  · intro h
    obtain ⟨hs, hy⟩ := (mem_planeRows _ _ _ _ _).mp h
    obtain ⟨b, hb⟩ := hy
    obtain ⟨v, hv⟩ := dotMap_surjective ha (dot g z)
    refine ⟨(0, b, v, 0), ?_⟩
    change dot a v = dot g z at hv
    simp [leftOne, hs, hb, hv]

end CyclicData

/-- General codimension-one preimage calculation. -/
theorem finrank_comap_plane (P : Submodule k (Vec k)) (f : Vec k →ₗ[k] Vec k)
    (hP : finrank k P = 2) (hsup : P ⊔ LinearMap.range f = ⊤) :
    finrank k (P.comap f) = 2 := by
  let q : Vec k →ₗ[k] (Vec k ⧸ P) := P.mkQ.comp f
  have hsurj : Function.Surjective q := by
    intro y
    obtain ⟨v, hv⟩ := P.mkQ_surjective y
    have hm : v ∈ P ⊔ LinearMap.range f := by rw [hsup]; trivial
    obtain ⟨a, ha, b, hb, hab⟩ := Submodule.mem_sup.mp hm
    obtain ⟨c, hc⟩ := hb
    refine ⟨c, ?_⟩
    change P.mkQ (f c) = y
    rw [hc, ← hv, ← hab, map_add]
    have hqa : P.mkQ a = 0 := by simpa using ha
    rw [hqa, zero_add]
  have hker : LinearMap.ker q = P.comap f := by
    ext v
    simp [q, LinearMap.mem_ker]
  have hrange : LinearMap.range q = ⊤ := LinearMap.range_eq_top.mpr hsurj
  have hquot := Submodule.finrank_quotient_add_finrank P
  have hquot' : finrank k (Vec k ⧸ P) = 1 := by
    rw [hP, finrank_vec] at hquot
    omega
  have hdim := LinearMap.finrank_range_add_finrank_ker q
  rw [hrange, hker] at hdim
  have hdim' : 1 + finrank k (P.comap f) = 3 := by
    simpa [hrange, hker, hquot'] using hdim
  omega

namespace CyclicData

/-- The colon subspace is again a plane. -/
theorem finrank_colonPlane (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) (a g : Vec k)
    (ha : finrank k (LinearMap.range (D.mul i a)) = 2)
    (hplane : finrank k (Submodule.span k ({a, g} : Set (Vec k))) = 2) :
    finrank k (D.colonPlane i a g) = 2 := by
  apply finrank_comap_plane _ _ ha
  exact D.ranges_sup_eq_top hD i a g hplane

/-- The two-generator colon returns to the same family of generated row ideals. -/
theorem plane_colon_closed (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) {a g : Vec k} (ha : a ≠ 0)
    (hg : g ∉ Submodule.span k {a})
    (hr : finrank k (LinearMap.range (D.mul i a)) = 2)
    (hplane : finrank k (Submodule.span k ({a, g} : Set (Vec k))) = 2) :
    (LinearMap.range (D.leftOne i a)).comap (D.leftOne i g) =
      D.rowGenerated (next i) (D.colonPlane i a g) := by
  rw [D.colon_eq_planeRows i ha hg]
  rw [D.rowGenerated_eq_planeRows hD (next i) _
    (by rw [D.finrank_colonPlane hD i a g hr hplane] <;> omega)]

/-- The last colon case: a plane and one element outside it. -/
theorem full_colon_eq_positive_rows (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) (U : Submodule k (Vec k)) (hU : finrank k U = 2)
    {g : Vec k} (hg : g ∉ U) :
    (D.rowGenerated i U).comap (D.leftOne i g) =
      planeRows (⊤ : Submodule k (Vec k)) := by
  rw [D.rowGenerated_eq_planeRows hD i U (by omega)]
  ext r
  rcases r with ⟨s, y, z, t⟩
  change D.leftOne i g (s, y, z, t) ∈ planeRows U ↔
    (s, y, z, t) ∈ planeRows (⊤ : Submodule k (Vec k))
  change (0, s • g, D.mul i g y, dot g z) ∈ planeRows U ↔
    (s, y, z, t) ∈ planeRows (⊤ : Submodule k (Vec k))
  simp only [mem_planeRows, Submodule.mem_top, eq_self_iff_true, and_true, true_and]
  constructor
  · intro hs
    by_contra hsz
    apply hg
    have hh := U.smul_mem s⁻¹ hs
    simpa [smul_smul, hsz] using hh
  · intro hs
    simp [hs]

/-- The full-space colon is the ideal generated by all degree-one elements
at the adjacent vertex. -/
theorem full_colon_closed (D : CyclicData k) (hD : D.Regular)
    (i : Vertex) (U : Submodule k (Vec k)) (hU : finrank k U = 2)
    {g : Vec k} (hg : g ∉ U) :
    (D.rowGenerated i U).comap (D.leftOne i g) =
      D.rowGenerated (next i) (⊤ : Submodule k (Vec k)) := by
  rw [D.full_colon_eq_positive_rows hD i U hU hg]
  rw [D.rowGenerated_eq_planeRows hD (next i) ⊤ (by simp)]

end CyclicData
end Ginzburg333
